### ISSUE TITLE
接收数据的时候还是会卡死。

### ISSUE THREAD

**Issue by xhanglizhu** [silencefun/ComTest#1]
从Android里发送数据出去没有问题，
但是，接收数据的时候Android会卡死。
AndroidStudio_3.0_COMTEST

**Comment by silencefun** [comment]
https://github.com/silencefun/ComTest/blob/master/AndroidStuido_3.0_COMTEST/ComTest_AndroidStudio3.0/app/src/main/java/com/silencefun/comtest/MainActivity.java

中第495行

  private class SerialControl extends SerialHelper 

注释有说明

            //数据接收量大或接收时弹出软键盘，界面会卡顿,可能和6410的显示性能有关
            //直接刷新显示，接收数据量大时，卡顿明显，但接收与显示同步。
            //用线程定时刷新显示可以获得较流畅的显示效果，但是接收数据速度快于显示速度时，显示会滞后。
            //最终效果差不多-_-，线程定时刷新稍好一些。


这是从eclipse 复制过来源码就是这样的。

我自己去年测试的结果是 在1G 运存的 确实卡顿 可能有两方面原因：
1.设备配置太低 处理器也垃圾
2.数据量太大，

在https://github.com/silencefun/ComTest/blob/master/AndroidStuido_3.0_COMTEST/ComTest_AndroidStudio3.0/app/src/main/java/com/silencefun/comtest/SerialHelper.java

就是上边那个 对象父类中 115-139 行
有一个接收 即读取线程 有一个 等待时间，可以尝试更改这个值来
  private class ReadThread extends Thread {
        @Override
        public void run() {
            super.run();
            while (!isInterrupted()) {
                try {
                    if (mInputStream == null) return;
                    byte[] buffer = new byte[512];
                    int size = mInputStream.read(buffer);
                    if (size > 0) {
                        ComBean ComRecData = new ComBean(sPort, buffer, size);
                        onDataReceived(ComRecData);
                    }
                    try {
                        **Thread.sleep(50);//延时50ms**
                    } catch (InterruptedException e) {
                        e.printStackTrace();
                    }
                } catch (Throwable e) {
                    e.printStackTrace();
                    return;
                }
            }
        }
    }

**Comment by xhanglizhu** [comment]
@silencefun 感谢回复。卡死的原因，是因为发送的字节超过8，PC端模拟串口，发送ASCII字符串，超过8位会卡死 。
现在要研究USB 转 串口的流程了。
再次感谢。
