### ISSUE TITLE
奇偶校验的问题

### ISSUE THREAD

**Issue by codeayit** [silencefun/ComTest#2]
通过奇偶校验还是不行，楼主问题解决了么

**Comment by silencefun** [comment]
C文件 用这个里边的试试，可能最开的是那几个.so 是没改的，
这个我之前用的全都测过了 是可以的，不过校验方式我记得并没有写全，已经半年没有接触硬件相关的的问题了，先试试：

Android 串口开发 支持N-8-1（数据位停止位校验方式） 设定https://www.jianshu.com/p/0868e90303be

**Comment by codeayit** [comment]
发送可以  但是接受就不对了

**Comment by silencefun** [comment]
主要是在 校验方式设定的位置。

switch(nEvent) //设置校验位
{
    case 'o':
    case 'O':

        newtio.c_cflag |= (PARODD | PARENB);
        newtio.c_iflag |= INPCK;
        LOGE("设置校验位O奇校验位");

        break;
    case 'e':
    case 'E':

        newtio.c_cflag |= PARENB;
        newtio.c_cflag &= ~PARODD;
        newtio.c_iflag |= INPCK;



        LOGE("设置校验位E偶校验位");

        break;

    case 'N':
    case 'n':
        newtio.c_cflag &= ~PARENB; //清除校验位


        LOGE("设置校验位N");
        break;


    default:
        newtio.c_cflag &= ~PARENB; //清除校验位
        LOGE("设置校验位默认N");
        break;

}

我当时测得都是ok 的 用了 串口调试助手以及2种硬件通讯测试过是没问题的。

或者 在搜一下 linux 环境下 串口编程 的这部分设定 参考替换一下。

当然 也不排除你的板子是有问题的。如果可以再换个试一试。

当时接手的 供货商给的 android 5.1  某种板子， 每次吐出来1个字节的数据，然后中断，然后再突出下一个，这里的C里边这种写法肯定是不对的，当然我认为 板子的 这种数据流输出也是不对的，当时的做法是 连续接收 多少秒后再把数据抛给java层，仅供参考。

**Comment by codeayit** [comment]
哦哦  问题应该是  一次一个字节流的问题   因为接受一个字节流 也是ok 的   只要长度超过1  从第二个开始不对了  恩恩  非常感谢

**Comment by codeayit** [comment]
问题解决了  双手奉上 ：
   /*设置奇偶校验位*/
    switch( nEvent )
    {
        case 'o':  /*奇校验*/
        case 'O':
            newttys1.c_cflag |= PARENB;/*开启奇偶校验*/
            newttys1.c_iflag |= (INPCK | ISTRIP);/*INPCK打开输入奇偶校验；ISTRIP去除字符的第八个比特  */
            newttys1.c_cflag |= PARODD;/*启用奇校验(默认为偶校验)*/
            break;
        case 'E':/*偶校验*/
        case 'e':
            newttys1.c_cflag |= PARENB; /*开启奇偶校验  */
            newttys1.c_iflag |= ( INPCK | ISTRIP);/*打开输入奇偶校验并去除字符第八个比特*/
            newttys1.c_cflag &= ~PARODD;/*启用偶校验*/

            newttys1.c_iflag |= (INPCK | ISTRIP);
            newttys1.c_cflag |= PARENB;
            newttys1.c_cflag &= ~PARODD;

            break;
        case 'N': /*无奇偶校验*/
        case 'n':
            newttys1.c_cflag &= ~PARENB;
            break;
    }
