### ISSUE TITLE
手机调试的问题

### ISSUE THREAD

**Issue by OTZ123** [silencefun/ComTest#3]
请问能不能在手机上发送232或485信号，还是说需要自行研究usb转串口通信

**Comment by silencefun** [comment]
抱歉这几天太忙了没有看，

手机上理论上是不就可以的，

差不多大半年没有做这些了，据之前的了解，大部分手机rom都是不支持串口的，

但是原理来说，支持OTG功能的 的 手机或者可以 使用usb转一下，这点类似于 linux 下的 加载设备，但是 底层协议肯定是不一样的，如果 定制 底层协议应该可以。

所以感觉使用 手机通过 usb 直连 硬件 串口 通信，再现有的 android 手机大概是行不通的，一般都是加载的 usb设备。

**Comment by OTZ123** [comment]
多谢大佬，短时间内只能寻找其他解决方案了

**Comment by OTZ123** [comment]
多谢大佬，短时间内只能寻找其他解决方案了
